CREATE TABLE IMAGES(
ID INT,
"NAME" VARCHAR(50) NOT NULL,
IMG VARBINARY(MAX) NOT NULL
CONSTRAINT PK_IMG PRIMARY KEY (ID)
)

drop table IMAGES


select * from IMAGES





CREATE TABLE WEB_USERS(
USERNAME VARCHAR(25),
EMAIL VARCHAR(70) NOT NULL,
"PASSWORD" VARCHAR(50) NOT NULL,
CONSTRAINT PK_WEB_USERS PRIMARY KEY (USERNAME)
)

INSERT INTO WEB_USERS VALUES ('Tegra', 'myemail@gmail.com','password1');

select * from WEB_USERS

drop table USERS


CREATE TABLE EMPLOYEES(
USERNAME VARCHAR(25),
"PASSWORD" VARCHAR(50) NOT NULL,
CONSTRAINT PK_EMP PRIMARY KEY (USERNAME)
)


INSERT INTO EMPLOYEES VALUES ('Employee1','password1');

select * from EMPLOYEES

drop table EMPLOYEES